Laba5 - Geometry - Goryachkin
Maxsmile123/ZZZ-Computer-Science-Course pull request #127
Opened 2023-10-13 21:14 UTC by Winterfulllll

2023-10-16 02:11 UTC, Maxsmile123 requested changes

2023-10-16 02:11 UTC, Maxsmile123 commented on tasks/geometry/tasks/9/solution.h
> +        int is_inside = CheckZone(p);
Ты создаешь эту переменную заново каждый раз в цикле. В итоге будет ITERATIONS раз создание и удаление переменной... Давай вынесем её объявление за цикл

2023-10-16 02:20 UTC, Maxsmile123 requested changes

2023-10-16 02:20 UTC, Maxsmile123 commented on tasks/geometry/tasks/9/solution.h
> +        i = Mod((Abs(Max(p.x * (k + FOUR), p.y * (k + FIVE))) - Abs(Min(p.y * (k + SIX), l * (k + SEVEN)))), TWENTY);
А нельзя сразу писать p.x = ???

2023-10-17 11:33 UTC, Maxsmile123 requested changes

2023-10-17 11:33 UTC, Maxsmile123 commented on tasks/geometry/tasks/9/solution.h
> +        i = Mod((Abs(Max(p.x * (k + FOUR), p.y * (k + FIVE))) - Abs(Min(p.y * (k + SIX), l * (k + SEVEN)))), TWENTY);
Всё ещё в силе

2023-10-17 13:58 UTC, Winterfulllll commented on tasks/geometry/tasks/9/solution.h
> +        i = Mod((Abs(Max(p.x * (k + FOUR), p.y * (k + FIVE))) - Abs(Min(p.y * (k + SIX), l * (k + SEVEN)))), TWENTY);
Если имеется в виду запись сразу в переменную p.x в цикле, то нельзя, так как значение предыдущей операции нам ещё будет нужно при поиске p.y и l на данной итерации, такого рода приём уже применен в переменной l, там он уместен, так как ей присваивается значение в цикле в последнюю очередь и значение её предыдущей итерации нам не потребуется при поиске какой-то другой переменной

2023-10-18 14:19 UTC, Maxsmile123 commented on tasks/geometry/tasks/9/solution.h
> +        i = Mod((Abs(Max(p.x * (k + FOUR), p.y * (k + FIVE))) - Abs(Min(p.y * (k + SIX), l * (k + SEVEN)))), TWENTY);
Принято, оставляем как есть

2023-10-18 14:20 UTC, Maxsmile123 approved these changes

2023-10-18 14:20 UTC, merged