Ivchenko Matvey, integers, week3 --- laba6
Maxsmile123/ZZZ-Computer-Science-Course pull request #140
Opened 2023-10-15 14:45 UTC by Matvey26

2023-10-16 02:28 UTC, Maxsmile123 requested changes

2023-10-16 02:28 UTC, Maxsmile123 commented on tasks/integers/tasks/13/solution.h
> +    scanf("%s", str_number);
Это серьёзная уязвимость, читай сообщение в ТГ

2023-10-16 02:28 UTC, Maxsmile123 commented on tasks/integers/tasks/13/solution.h
> +    // Теперь нужно узнать, сколько знаков будет в двоичном представлении
Вынести в отдельную функцию

2023-10-16 02:28 UTC, Maxsmile123 commented on tasks/integers/tasks/13/solution.h
> +    // Переводим число в двоичную систему счисления с добавлением нулей в середину
Вынести в отедльную функцию

2023-10-16 02:28 UTC, Maxsmile123 commented on tasks/integers/tasks/13/solution.h
> +#include <stdlib.h>
Тоже не понадобиться, читай тг

2023-10-16 02:28 UTC, Maxsmile123 commented on tasks/integers/tasks/13/solution.h
> +const size_t MAX_NUMBER_LEN = 20;
NUMBER - лишнее. ОЧевидно, что длина - это число, а не что-то иное

2023-10-16 02:28 UTC, Maxsmile123 commented on tasks/integers/tasks/13/solution.h
> +    printf("Enter the number with leading zeros: ");
Scanf кстати тоже умеет в форматированные строки:
```scanf("Enter the number with leading zeros: %s", str_number);```

2023-10-17 19:24 UTC, Matvey26 commented on tasks/integers/tasks/13/solution.h
> +    scanf("%s", str_number);
Исправлено. Вернее сказать, было убрано за ненадобностью (изменились условия ввода)

2023-10-17 19:27 UTC, Matvey26 commented on tasks/integers/tasks/13/solution.h
> +    // Теперь нужно узнать, сколько знаков будет в двоичном представлении
Перевод числа-строки в число был убран за ненадобность (изменились условия ввода).
Строчка, которая берёт число по модулю, впоследствии стала ненужна, т.к. было найдено более лаконичное решение, которое не требовало, что число было положительным

2023-10-17 19:33 UTC, Matvey26 commented on tasks/integers/tasks/13/solution.h
> +    // Переводим число в двоичную систему счисления с добавлением нулей в середину
Исправлено. Решение было вынесено в функцию  Solve(*args), которая принимает в качестве параметров само число и количество нулей и возвращает ответ на поставленную задачу

2023-10-17 19:33 UTC, Matvey26 commented on tasks/integers/tasks/13/solution.h
> +#include <stdlib.h>
Действительно не понадобилось

2023-10-17 19:34 UTC, Matvey26 commented on tasks/integers/tasks/13/solution.h
> +const size_t MAX_NUMBER_LEN = 20;
Принял к сведению. Переменная была убрана за ненадобностью (изменились условия ввода)

2023-10-17 19:34 UTC, Matvey26 commented on tasks/integers/tasks/13/solution.h
> +    printf("Enter the number with leading zeros: ");
Было убрано за ненадобностью (изменились условия ввода)

2023-10-18 14:48 UTC, Maxsmile123 approved these changes

2023-10-18 14:48 UTC, merged