Geometry of Sakana
Maxsmile123/ZZZ-Computer-Science-Course pull request #155
Opened 2023-10-20 12:15 UTC by UnlimitedRule8ook

проверка-проверка

2023-10-20 14:56 UTC, Maxsmile123 requested changes

2023-10-20 15:16 UTC, UnlimitedRule8ook commented on tasks/geometry/tasks/7/solution.h
> +    double x;
Там же в формуле изменения координат присутствует деление "/".Или же имеется в виду деление нацело?

2023-10-20 15:18 UTC, UnlimitedRule8ook commented on tasks/geometry/tasks/7/solution.h
> +double Truefmod(double a, double b) {
Первая функция - просто оператор % для флотов, а вторая - деление по модулю, как в питоне. Разнес их, чтобы не писать много математики в одной.

2023-10-23 15:23 UTC, Maxsmile123 commented on tasks/geometry/tasks/7/solution.h
> +    double x;
Да, имеется в виду деление нацело

2023-10-23 15:24 UTC, Maxsmile123 commented on tasks/geometry/tasks/7/solution.h
> +double Truefmod(double a, double b) {
Для флотов можно убрать, так как используем только целые числа

2023-10-23 15:32 UTC, Maxsmile123 requested changes

2023-10-23 15:32 UTC, Maxsmile123 commented on tasks/geometry/tasks/7/solution.h
> +    } else if (hit_counter > 0) {
А зачем эта проверка? Он либо 0, либо больше нуля))

2024-01-07 14:46 UTC, Maxsmile123 approved these changes

2024-01-07 14:46 UTC, merged