Geometry_15var_mg
Maxsmile123/ZZZ-Computer-Science-Course pull request #159
Opened 2023-10-20 14:41 UTC by mashulyag

2023-10-20 14:57 UTC, Maxsmile123 requested changes
Надо файл убрать

2023-10-20 14:57 UTC, Maxsmile123 requested changes

2023-10-20 14:57 UTC, Maxsmile123 commented on tasks/geometry/tasks/15/solution.h
> -#pragma once
Это удалять нельзя

2023-10-21 05:44 UTC, closed without merging

2023-10-21 08:20 UTC, mashulyag commented
geometry

2023-10-21 08:21 UTC, mashulyag commented
g