Geometry6
Maxsmile123/ZZZ-Computer-Science-Course pull request #166
Opened 2023-10-20 21:01 UTC by Stimch

2023-10-20 21:30 UTC, Stimch commented
Исправил ошибки

2023-10-25 21:27 UTC, Maxsmile123 requested changes

2023-10-25 21:27 UTC, Maxsmile123 commented on tasks/nam/tasks/19/solution.nam
Это лишнее

2023-10-25 21:27 UTC, Maxsmile123 commented on tasks/geometry/tasks/6/solution.h
> +    int popal = 0;
транслит запрещен

2023-10-25 21:27 UTC, Maxsmile123 commented on tasks/geometry/tasks/6/solution.h
> +const int STEPS_COUNT = 50;
MAX_STEPS звучит лучше

2023-10-26 19:11 UTC, Stimch commented
Исправил

2023-10-26 19:22 UTC, Stimch reviewed
Исправил переменные

2023-10-27 16:05 UTC, Maxsmile123 approved these changes

2023-10-27 16:06 UTC, Maxsmile123 approved these changes
Замержим после защиты НАМ

2023-11-25 10:14 UTC, merged