bitsets_4 (Goryachkin)
Maxsmile123/ZZZ-Computer-Science-Course pull request #177
Opened 2023-10-21 21:35 UTC by Winterfulllll

2023-10-27 16:19 UTC, Maxsmile123 requested changes

2023-10-27 16:19 UTC, Maxsmile123 commented on tasks/bitsets/tasks/4/solution.h
> +const int32_t A_INDEX = 'a' - 'a';
А если всё это занести в множество гласных букв? Проверка тогда будет очень короткой

2023-10-27 16:19 UTC, Maxsmile123 commented on tasks/bitsets/tasks/4/solution.h
> +    return (index != A_INDEX && index != E_INDEX && index != I_INDEX && index != O_INDEX && index != Y_INDEX);
Лучше реализовать через Битсет

2023-10-27 16:19 UTC, Maxsmile123 commented on tasks/bitsets/tasks/4/solution.h
> +    Bitset previous_word_letters_set = 0;
Немного не понял, зачем тебе предыдущее слово хранить. В задании речь про одно слово с повторяющимися

2023-10-27 16:19 UTC, Maxsmile123 commented on tasks/bitsets/tasks/4/solution.h
> +    Bitset previous_word_letters_set = 0;
Всё же разобрался. Смутило в названии переменных word. Придумай другой способ нэйминга, слово - это пачка символов, разделённая пробелами. У тебя это явно не то обозначает

2023-10-28 06:10 UTC, Maxsmile123 requested changes

2023-10-28 06:10 UTC, Maxsmile123 commented on tasks/bitsets/tasks/4/solution.h
> +    return ((WITHOUT_VOWELS >> index) & 1) & (0 | (1 << index));
Фигня какая-то. Можно проще

2023-10-28 06:10 UTC, Maxsmile123 commented on tasks/bitsets/tasks/4/solution.h
> +    return ((WITHOUT_VOWELS >> index) & 1) & (0 | (1 << index));
```0 | (1 << index)``` всегда = ```1 << index```

2023-10-28 06:10 UTC, Maxsmile123 commented on tasks/bitsets/tasks/4/solution.h
> +    return ((WITHOUT_VOWELS >> index) & 1) & (0 | (1 << index));
Нужно было множество из одной гласной сравнить (найти объединение) с множеством всех гласных. А тут что-то из разделов чёрной магии

2023-10-28 09:00 UTC, Winterfulllll commented on tasks/bitsets/tasks/4/solution.h
> +    return ((WITHOUT_VOWELS >> index) & 1) & (0 | (1 << index));
Исправил

2023-11-01 15:16 UTC, Maxsmile123 approved these changes

2023-11-01 15:16 UTC, merged