BITSETS_27 Ивченко
Maxsmile123/ZZZ-Computer-Science-Course pull request #179
Opened 2023-10-23 09:22 UTC by Matvey26

2023-10-27 16:22 UTC, Maxsmile123 requested changes

2023-10-27 16:22 UTC, Maxsmile123 commented on tasks/bitsets/tasks/27/solution.h
> +            if ((word != 0u) && ((word & VOWELS) == VOWELS)) {
А зачем тут эта проверка ```(word != 0u)```?

2023-10-27 16:28 UTC, Matvey26 commented on tasks/bitsets/tasks/27/solution.h
> +            if ((word != 0u) && ((word & VOWELS) == VOWELS)) {
Уже не помню, сейчас уберу

2023-10-28 06:14 UTC, Maxsmile123 approved these changes

2023-10-28 06:14 UTC, merged