INTEGERS_19 melnikova
Maxsmile123/ZZZ-Computer-Science-Course pull request #187
Opened 2023-10-25 10:18 UTC by nimelnikova

2023-10-25 22:09 UTC, Maxsmile123 requested changes

2023-10-25 22:09 UTC, Maxsmile123 commented on tasks/integers/tasks/19/solution
Это лишнее

2023-10-25 22:09 UTC, Maxsmile123 commented on tasks/integers/tasks/19/solution.h
> +        number = -number;  // Обработка отрицательных чисел
А это всегда ли работает? 
Во-первых, почему просто не написать abs?
Во-вторых, что будет, если пришло число INT_MIN?

2023-10-25 22:09 UTC, Maxsmile123 commented on tasks/integers/tasks/19/solution.h
> +    if (number < TEN) {
Почему? Давай вынесем эту проверку в функцию IsLessThenTwoDigits(int64_t num). Согласись, такой код:
```
if (IsLessThenTwoDigits(number)) {
    return 0;
}
```
Выглядит очевиднее, чем нынешний вариант

2023-10-27 15:29 UTC, nimelnikova commented on tasks/integers/tasks/19/solution.h
> +    if (number < TEN) {
исправила, спасибо

2023-10-28 06:53 UTC, Maxsmile123 requested changes

2023-10-28 06:53 UTC, Maxsmile123 commented on tasks/integers/tasks/19/solution
Это лишнее

2023-10-28 06:53 UTC, Maxsmile123 commented on tasks/integers/tasks/19/solution.h
> +int64_t IsLessThenTwoDigits(int64_t num) {
Зачем возвращать тут int64_t?

2023-10-28 06:53 UTC, Maxsmile123 commented on tasks/integers/tasks/19/solution.h
> +        return 0;
Функция звучит как "Меньше двух цифр". 0 означает false, 1 - true. Твоя функция возвращает false, когда цифр меньше двух, а true - когда их больше или равно. Выглядит странно

2023-10-28 06:53 UTC, Maxsmile123 commented on tasks/integers/tasks/19/solution.h
> +    int64_t number = Abs(NUMBER);  // comment this line
А если пришло INT64_T_MIN?

2023-10-28 06:53 UTC, Maxsmile123 commented on tasks/integers/tasks/19/solution.h
> +    int64_t number_of_digits = 1;
Переменная не хранит кол-во цифр... Нужно название по-лучше. 
Я бы назвал так: Max_digit_of_number
Хотя и это не очень... Английский язык не различает слов "Разряд и цифра", к сожалению... 
Но переменная явно не про количество

2023-10-28 15:47 UTC, nimelnikova commented on tasks/integers/tasks/19/solution.h
> +        number = -number;  // Обработка отрицательных чисел
все поправила.

2023-11-01 15:31 UTC, Maxsmile123 requested changes

2023-11-01 15:31 UTC, Maxsmile123 commented on tasks/integers/tasks/19/solution
Этот файл всё ещё лишний

2023-11-01 15:31 UTC, Maxsmile123 commented on tasks/integers/tasks/19/solution.h
> +        return 0;
IsLessThenThreeDigits должна возвращать 1, когда цифр меньше трёх и 0, когда их больше либо равно трём. Это будет соответствовать названию. Сейчас это не так

2023-11-01 15:31 UTC, Maxsmile123 commented on tasks/integers/tasks/19/solution.h
> +    int64_t number = Abs(NUMBER);  // comment this line
Всё ещё сломается на числе -9 223 372 036 854 775 808

2023-11-01 22:44 UTC, nimelnikova commented on tasks/integers/tasks/19/solution.h
> +        return 0;
исправила

2023-11-06 11:51 UTC, merged