INTEGERS_VAR25_DmitryNaypak
Maxsmile123/ZZZ-Computer-Science-Course pull request #189
Opened 2023-10-25 20:27 UTC by DmitryNai

2023-10-28 07:05 UTC, Maxsmile123 requested changes

2023-10-28 07:05 UTC, Maxsmile123 commented on tasks/integers/tasks/25/solution.h
> +    if (INPUT_NUMBER >= 0) {
Зачем? Это неважно в разрезе задачи. Цифры положительного и отрицательного числа ничем не отличаются. Числа - отличаются, цифры - нет

2023-10-28 07:05 UTC, Maxsmile123 commented on tasks/integers/tasks/25/solution.h
> +            int64_t digit_number = (number / (Power(TEN, (k - 1))) % Power(TEN, 1));
Что за digit_number?

2023-10-28 07:05 UTC, Maxsmile123 commented on tasks/integers/tasks/25/solution.h
> +            int64_t digit_number = (number / (Power(TEN, (k - 1))) % Power(TEN, 1));
А почему нельзя было пойти справа налево? Так бы ты мог накапливать текущий разряд, а не вычислять его заново каждый раз через Power

2023-10-28 08:42 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +    if (INPUT_NUMBER >= 0) {
> Зачем? Это неважно в разрезе задачи. Цифры положительного и отрицательного числа ничем не отличаются. Числа - отличаются, цифры - нет

Т.к нам нельзя использовать массивы, я прохожу по числу через математику, а следовательно если число отрицательное, то постоянно у меня отрицательные числа. И при выводе получается: -1-1-3-3-5(если входное число меньше 0). Поэтому и сделал такую проверку.

2023-10-28 08:43 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +            int64_t digit_number = (number / (Power(TEN, (k - 1))) % Power(TEN, 1));
> А почему нельзя было пойти справа налево? Так бы ты мог накапливать текущий разряд, а не вычислять его заново каждый раз через Power
Я так сделал, потому что при проходе справа налево у меня получается число в реверсе. Я избавился от последующего алгоритма реверса через такой код

2023-10-28 08:43 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +            int64_t digit_number = (number / (Power(TEN, (k - 1))) % Power(TEN, 1));
> > А почему нельзя было пойти справа налево? Так бы ты мог накапливать текущий разряд, а не вычислять его заново каждый раз через Power
Я так сделал, потому что при проходе справа налево у меня получается число в реверсе. Я избавился от последующего алгоритма реверса через такой код

2023-10-28 08:44 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +            int64_t digit_number = (number / (Power(TEN, (k - 1))) % Power(TEN, 1));
> А почему нельзя было пойти справа налево? Так бы ты мог накапливать текущий разряд, а не вычислять его заново каждый раз через Power

Я так сделал потому что при проходе справа налево у меня получается реверснутое число. Этим кодом я избавился от последующего кода обратного реверса числа.

2023-10-28 10:03 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +const int8_t ONE = 1;
> Зачем эта константа? Линтеры не ругаются на 0 и 1

Исправил

2023-10-28 10:03 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +int Power(int32_t start_number, int32_t degree) {
> А если степень отрицательная? Давай использовать uint32_t

Исправил

2023-10-28 10:03 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +    int32_t count = 0;
> Счётчик чего?

Исправил

2023-10-28 10:03 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +    int64_t number = INPUT_NUMBER;
> Что за число? просто число? input_num звучит лучше

Исправил

2023-10-28 10:04 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +            int64_t digit_number = (number / (Power(TEN, (k - 1))) % Power(TEN, 1));
> Что за digit_number?

Исправил, заменил на digit(цифра)

2023-11-01 15:35 UTC, Maxsmile123 requested changes

2023-11-01 15:35 UTC, Maxsmile123 commented on tasks/integers/tasks/25/solution.h
> +    if (INPUT_NUMBER >= 0) {
Может использовать функцию abs и во много раз сократить код?

2023-11-01 15:35 UTC, Maxsmile123 commented on tasks/integers/tasks/25/solution.h
> +    if (INPUT_NUMBER >= 0) {
Обработав при этом отдельно INT_MIN

2023-11-02 08:47 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +    if (INPUT_NUMBER >= 0) {
> Может использовать функцию abs и во много раз сократить код?

Исправил

2023-11-02 11:19 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +    if (INPUT_NUMBER >= 0) {
> Может использовать функцию abs и во много раз сократить код?

Исправил. Пришлось немного переписать код.

2023-11-02 11:20 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +            int64_t digit_number = (number / (Power(TEN, (k - 1))) % Power(TEN, 1));
> А почему нельзя было пойти справа налево? Так бы ты мог накапливать текущий разряд, а не вычислять его заново каждый раз через Power

Исправил.

2023-11-06 12:01 UTC, Maxsmile123 requested changes

2023-11-06 13:47 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +const int32_t TEN = 10;
Исправил.

2023-11-06 13:47 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +        int64_t is_negative = Sign(input_number);
Исправил.

2023-11-06 13:47 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +        int64_t digit = (number / power_10) % TEN;
Исправил.

2023-11-06 13:47 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +const int32_t TEN = 10;
> Нужно убрать константы, больше неактуально

Исправил

2023-11-06 13:47 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +        int64_t is_negative = Sign(input_number);
> Название неверное. is_negative предполагает да(1) или нет (0). У тебя возможные значения 1, 0 и -1

Исправил.

2023-11-06 13:47 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +        int64_t digit = (number / power_10) % TEN;
> Вынеси создание переменной за цикл

Исправил.

2023-11-06 13:47 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +            digit -= (int64_t)(digit % 2 == 0);
> Зачем каст?

Исправил.

2023-11-06 13:48 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +int64_t Solve(int64_t number) {
> Абстрактное название. Я не понимаю, что эта функция делает

Исправил.

2023-11-06 13:48 UTC, DmitryNai commented on tasks/integers/tasks/25/solution.h
> +    int64_t power_10 = 1;
> Предполагается по названию, что здесь хранится степень десятки. А ты хранишь не степень, а само значение 10^power
> 
> P.s. (power_of_ten). Цифры в названии - почти всегда плохое решение.

Исправил.

2023-11-09 00:46 UTC, Maxsmile123 approved these changes

2023-11-09 00:47 UTC, merged