Bitsets_6 Surov Ivan
Maxsmile123/ZZZ-Computer-Science-Course pull request #199
Opened 2023-10-28 07:45 UTC by SurovIvan

2023-11-02 13:50 UTC, Maxsmile123 requested changes
Нужно сходить на защиту

2023-11-02 13:50 UTC, Maxsmile123 commented on tasks/bitsets/tasks/6/solution.h
> +    return (letter == 'a' || letter == 'e' || letter == 'i' || letter == 'u' || letter == 'y' || letter == 'o');
Заведи множество только гласных и находи этот ответ при помощи него

2023-11-02 13:50 UTC, Maxsmile123 commented on tasks/bitsets/tasks/6/solution.h
> +    int8_t flag = 0;
Это название не по кодстайлу

2023-11-02 13:50 UTC, Maxsmile123 commented on tasks/bitsets/tasks/6/solution.h
> +const uint32_t RIGHT_VOWELS = 17826048;
Что за Правые гласные?

2023-11-02 13:50 UTC, Maxsmile123 commented on tasks/bitsets/tasks/6/solution.h
> +            if (RIGHT_VOWELS == (RIGHT_VOWELS | word) && word != 0) {
Зачем проверка на то, что ворд не равен 0?

2023-11-05 13:46 UTC, SurovIvan commented on tasks/bitsets/tasks/6/solution.h
> +            if (RIGHT_VOWELS == (RIGHT_VOWELS | word) && word != 0) {
Если в слове не будет ни одной гласной, то будет выведено, что в слове только гласные 2-ого рода, хотя это не так

2023-11-06 12:12 UTC, Maxsmile123 requested changes

2023-11-06 12:12 UTC, Maxsmile123 commented on tasks/bitsets/tasks/6/solution.h
> +    int8_t word_found = 0;
is_word_found

2023-11-06 12:13 UTC, Maxsmile123 commented on tasks/bitsets/tasks/6/solution.h
> +            if (RIGHT_VOWELS == (RIGHT_VOWELS | word) && word != 0) {
Принял

2023-11-06 12:16 UTC, Maxsmile123 requested changes

2023-11-06 12:16 UTC, Maxsmile123 commented on tasks/bitsets/tasks/6/solution.h
> +    return ALL_VOWELS == (ALL_VOWELS | (1u << (letter - 'a')));
Кажется,
```return (ALL_VOWELS & (1u << (letter - 'a'))```
даст такой же ответ, а выглядит короче

2023-11-06 12:16 UTC, Maxsmile123 commented on tasks/bitsets/tasks/6/solution.h
> +const uint32_t VOWELS_SECOND_KIND = 17826048;
Const Bitset ...

2023-11-09 00:49 UTC, Maxsmile123 approved these changes

2023-11-09 00:50 UTC, merged