geometry21 Бельский
Maxsmile123/ZZZ-Computer-Science-Course pull request #201
Opened 2023-10-29 10:43 UTC by bleb1

2023-11-02 14:14 UTC, Maxsmile123 requested changes

2023-11-02 14:14 UTC, Maxsmile123 commented on tasks/geometry/tasks/21/solution.h
> +const int ELEVEN = 11;
Все константы кроме MAX_ITERATION -> MAX_ITERATIONS нужно убрать

2023-11-02 14:14 UTC, Maxsmile123 commented on tasks/geometry/tasks/21/solution.h
> +int Mod(int a, int b) {
А если b = 0?

2023-11-02 14:14 UTC, Maxsmile123 commented on tasks/geometry/tasks/21/solution.h
> +    int is_local_success = 0;
Зачем? Почему нельзя так: ```return (p.y >= p.x + TEN && p.y <= MINUS_ONE * p.x + TEN && p.x >= MINUS_TEN) ```

2023-11-02 14:14 UTC, Maxsmile123 commented on tasks/geometry/tasks/21/solution.h
> +    int is_global_success = 0;
global можно убрать

2023-11-02 14:14 UTC, Maxsmile123 commented on tasks/geometry/tasks/21/solution.h
> +        if (CheckZone(p) == 1) {
Если функция возвращает 1, то это уже true. Зачем сравнивать с единицей?

2023-11-02 14:14 UTC, Maxsmile123 commented on tasks/geometry/tasks/21/solution.h
> +        temp_l = l;
Это зачем? Вроде, с l проблем и не было

2023-11-03 12:48 UTC, bleb1 commented on tasks/geometry/tasks/21/solution.h
> +const int ELEVEN = 11;
но если их убрать, то эти числа будут вызывать ошибки как магические

2023-11-06 12:24 UTC, Maxsmile123 approved these changes

2023-11-06 12:24 UTC, merged