integers28 Бельский
Maxsmile123/ZZZ-Computer-Science-Course pull request #204
Opened 2023-10-29 11:13 UTC by bleb1

2023-11-02 14:20 UTC, Maxsmile123 requested changes

2023-11-02 14:20 UTC, Maxsmile123 commented on tasks/integers/tasks/28/solution.h
> +    if (number_in_10 < 0) {
Вынести в отдельную функцию

2023-11-06 12:26 UTC, Maxsmile123 requested changes

2023-11-06 12:26 UTC, Maxsmile123 commented on tasks/integers/tasks/28/solution.h
> +int32_t CheckOnMinus(int32_t number) {
IsNegative звучит лучше

2023-11-06 12:26 UTC, Maxsmile123 commented on tasks/integers/tasks/28/solution.h
> +int64_t Convertation(int32_t decimal_number) {
Что за конвертация? Давай точнее назовём функцию

2023-11-06 12:53 UTC, bleb1 commented on tasks/integers/tasks/28/solution.h
> +int64_t Convertation(int32_t decimal_number) {
Исправил

2023-11-06 12:53 UTC, bleb1 commented on tasks/integers/tasks/28/solution.h
> +int32_t CheckOnMinus(int32_t number) {
Исправил

2023-11-11 16:02 UTC, Maxsmile123 approved these changes

2023-11-11 16:02 UTC, merged