LINERIZATION_24 Ивченко
Maxsmile123/ZZZ-Computer-Science-Course pull request #205
Opened 2023-10-29 15:10 UTC by Matvey26

2023-11-02 14:31 UTC, Maxsmile123 requested changes

2023-11-02 14:31 UTC, Maxsmile123 commented on tasks/linerization/tasks/24/solution.h
> +        run = !(vertical.start == vertical.end && horizontal.start == horizontal.end);
А почему бы это условие не вставить в while?

2023-11-02 14:31 UTC, Maxsmile123 commented on tasks/linerization/tasks/24/solution.h
> +#define Sign(x, y) (y >= x) ? 1 : -1
Название не очень. Оно же не про знак, а про y >= x

2023-11-02 14:31 UTC, Maxsmile123 commented on tasks/linerization/tasks/24/solution.h
> +
Добавь вывод обычной матрицы и линеаризованной

2023-11-05 10:47 UTC, Matvey26 commented on tasks/linerization/tasks/24/solution.h
> +        run = !(vertical.start == vertical.end && horizontal.start == horizontal.end);
Это бы немного поменяло логику, мне нужен был один лишний проход в цикле. Но я нашёл более лаконичное условие

2023-11-05 11:03 UTC, Matvey26 commented on tasks/linerization/tasks/24/solution.h
> +
Добавил

2023-11-05 11:06 UTC, Matvey26 commented on tasks/linerization/tasks/24/solution.h
> +#define Sign(x, y) (y >= x) ? 1 : -1
Поменял на isLess, но теперь по логике должно возвращаться либо 1, либо 0. Поэтому я в коде буду умножать результат на два и вычитать единицу

2023-11-05 11:09 UTC, Matvey26 commented on tasks/linerization/tasks/24/solution.h
> +    int32_t is_horizontal = 0;
Решил оставить название этой переменной как is_horizontal (а не is_x_axis, например), чтобы она хоть как-то отделялась от структур Slice

2023-11-06 12:31 UTC, Maxsmile123 requested changes
Глянь на вывод. Обход не верный. Должно быть 1 2 3 4 5 ... n*n - 1
А у тебя линеризация просто построчно

2023-11-06 13:33 UTC, Matvey26 commented
> Глянь на вывод. Обход не верный. Должно быть 1 2 3 4 5 ... n*n - 1 А у тебя линеризация просто построчно

Ааа, я вообще неправильно понял суть задачи, подглядел у Вовы Горячкина, переделаю

2023-11-10 14:52 UTC, DmitryNai commented on tasks/linerization/tasks/24/solution.h
>      return 0;
Вынеси в отдельную функцию.

2023-11-11 16:09 UTC, merged