Bitsets_29
Maxsmile123/ZZZ-Computer-Science-Course pull request #214
Opened 2023-11-04 20:56 UTC by Stimch

2023-11-06 13:05 UTC, Maxsmile123 requested changes
Надо на защиту сходить

2023-11-06 13:05 UTC, Maxsmile123 commented on tasks/bitsets/tasks/29/solution.h
> +    char sentence[] = "Mama mYLa ramu";
Сделай через while( (c = getchar()) != EOF )
Не нужно использовать тут эту штуку с указателями/массивами

2023-11-06 13:05 UTC, Maxsmile123 commented on tasks/bitsets/tasks/29/solution.h
> +            count += static_cast<int>(bitset & 1);
В Си нет static_cast

2023-11-10 19:22 UTC, Stimch commented
Изменил код(почти полностью), ибо прошлая версия была действительно ужасной.

2023-11-11 06:06 UTC, Stimch commented
Поменял название функции, чтобы название отражало то, что делает функция

2023-11-11 16:12 UTC, Maxsmile123 approved these changes

2023-11-11 16:12 UTC, merged