MATRIX_8 Ивченко
Maxsmile123/ZZZ-Computer-Science-Course pull request #219
Opened 2023-11-06 18:56 UTC by Matvey26

2023-11-11 16:44 UTC, Maxsmile123 approved these changes

2023-11-11 16:44 UTC, Maxsmile123 commented on tasks/matrix/tasks/8/solution.h
> +        Matrix matrix = (Matrix)calloc(1, sizeof(Row));
А зачем? Давай просто упадём с ошибкой исполнения:
```
if (fp== NULL)
  {
      printf("ошибка открытия файла");
      abort();                                                  // аварийное завершение программы
  }
  ```

2023-11-11 16:44 UTC, Maxsmile123 commented on tasks/matrix/tasks/8/solution.h
> +    const char *filename = "matrix.txt";  // откуда читаем данные
Вставь вот такой путь - тогда CI запустит твой файл:
```"../tasks/matrix/tasks/8/matrix.txt"```

2023-11-11 16:44 UTC, Maxsmile123 requested changes
Нужно поправить

2023-11-11 17:10 UTC, Matvey26 commented on tasks/matrix/tasks/8/solution.h
> +    const char *filename = "matrix.txt";  // откуда читаем данные
Исправил

2023-11-11 17:10 UTC, Matvey26 commented on tasks/matrix/tasks/8/solution.h
> +        Matrix matrix = (Matrix)calloc(1, sizeof(Row));
Даже не знал про abort(), спасибо, исправил

2023-11-11 17:10 UTC, Matvey26 commented
> Нужно поправить

Поправил

2023-11-14 13:27 UTC, Maxsmile123 approved these changes

2023-11-14 13:28 UTC, merged