Bitset13
Maxsmile123/ZZZ-Computer-Science-Course pull request #230
Opened 2023-11-10 10:00 UTC by sergey162

2023-11-11 17:25 UTC, Maxsmile123 requested changes

2023-11-11 17:25 UTC, Maxsmile123 commented on tasks/bitsets/tasks/13/solution.h
> +void Checker(uint8_t count, uint8_t max_glasn) {
Транслит запрещен

2023-11-11 17:25 UTC, Maxsmile123 commented on tasks/bitsets/tasks/13/solution.h
> +void Checker(uint8_t count, uint8_t max_glasn) {
Не понятно, что проверяет функция. Нужно лучшее название

2023-11-11 17:25 UTC, Maxsmile123 commented on tasks/bitsets/tasks/13/solution.h
> +        if (c == 'a' || c == 'e' || c == 'o' || c == 'i' || c == 'u' || c == 'y') {
Лучше создать множество всех гласных и проверять через него. Получится элегантнее

2023-11-11 17:25 UTC, Maxsmile123 commented on tasks/bitsets/tasks/13/solution.h
> +    const uint8_t max_glasn = 6;
транслит

2023-11-11 17:25 UTC, Maxsmile123 commented on tasks/bitsets/tasks/13/solution.h
> +    const uint8_t lens = 26;
Почему lens? Зачем множественное число

2023-11-11 17:25 UTC, Maxsmile123 commented on tasks/geometry/tasks/11/solution.h
> +        Point p;
Это плохо, ты её MAX_ITERATIONS раз создаёшь и удаляешь со стека

2023-11-11 17:25 UTC, Maxsmile123 commented on tasks/geometry/tasks/11/solution.h
> +    for (int i = 0; i < MAX_ITERATIONS; ++i) {
Надо бы заменить на k, как в условии

2023-11-11 17:25 UTC, Maxsmile123 commented on tasks/geometry/tasks/11/solution.h
> +int Remain(int divisible, int divider) {
Лучше назвать Mod

2023-11-11 17:25 UTC, Maxsmile123 commented on tasks/geometry/tasks/11/solution.h
Задача засчитывается с 60-тью баллами из 100

2023-11-11 17:25 UTC, Maxsmile123 commented on tasks/integers/tasks/4/solution.h
Задача принята

2023-11-11 17:25 UTC, Maxsmile123 commented on tools/run_linter.sh
Надо удалить это изменение, я не смогу его замержить

2023-11-14 13:48 UTC, Maxsmile123 requested changes

2023-11-14 13:48 UTC, Maxsmile123 commented on tasks/bitsets/tasks/13/solution.h
> +void CheckVowelFreedom(Bitset bitset) {
Не понял название. Свобода гласных?

2023-11-14 13:48 UTC, Maxsmile123 commented on tasks/bitsets/tasks/13/solution.h
> +    if (count < max_vowels) {
Ты считаешь кол-во букв в Битсете и сравниваешь его с 6. Что тебе это даст?

2023-11-14 13:48 UTC, Maxsmile123 commented on tasks/bitsets/tasks/13/solution.h
> +    CheckVowelFreedom(bitset);
Почему ты считаешь это после всего ввода? Вопрос про слова, а не весь текст. Слово - это чары, разделённые пробелами.

2023-11-14 13:48 UTC, Maxsmile123 commented on tasks/bitsets/tasks/13/solution.h
Задача решена неверно. Следующая проверка будет последней для этой задачи

2023-11-14 13:48 UTC, Maxsmile123 commented on tools/run_linter.sh
Я не выставлю итоговые баллы за задачу, пока не уберёшь это. Я не могу твой ПР замержить. Изменение этого файла способно разломать весь CI у всех

2023-11-14 20:00 UTC, sergey162 commented on tasks/bitsets/tasks/13/solution.h
> +    if (count < max_vowels) {
Я знаю, что гласных 6 в Английском алфавите, поэтому сравниваю с 6

2023-11-15 16:26 UTC, Maxsmile123 requested changes

2023-11-15 16:26 UTC, Maxsmile123 commented on tasks/bitsets/tasks/13/solution.h
> +    if (count < max_vowels) {
Твоя функция работает в предположении, что ты добавляешь в множество только гласные. Добавление происходит вне функции, поэтому у меня это и вызвало кучу недопонимания. 

Стоит выбрать другую логику проверки на гласные, например, используя объединение с заранее известным множеством всех гласных. Тогда не нужно понимать, как было собрано твоё множество, пришедшее на вход - функция отработает для любых множеств. К тому же стоит выбрать название удачнее: "Свобода гласных" звучит чертовски не понятно.

```IsAllVowelsInWord``` звучит понятнее и очевиднее. Также стоит изменить сигнатуру функции и сделать её bool - true, если все встречаемые гласные встретились и false - если не все. 

А логику печати нужно вынести в main, потому что сама функция не должна интерпретировать свой результат, она его лишь считает, а интерпретацией занимается уже вызывающая функция.

2023-11-15 16:26 UTC, Maxsmile123 commented on tasks/bitsets/tasks/13/solution.h
> +    CheckVowelFreedom(bitset);
Решили вопрос, всё верно, речь про весь текст в задании

2023-11-18 14:18 UTC, closed without merging