matrix22 Бельский
Maxsmile123/ZZZ-Computer-Science-Course pull request #244
Opened 2023-11-12 10:04 UTC by bleb1

2023-11-14 14:05 UTC, Maxsmile123 commented on tasks/matrix/tasks/22/solution.h
> +int32_t MinInd(int32_t a, int32_t b, int32_t i, int32_t mini_x) {
i -> a_i 
mini_x -> b_i

2023-11-14 14:06 UTC, Maxsmile123 commented on tasks/matrix/tasks/22/solution.h
> +        temp = matrix[mini_x][j];
Вынеси этот код в функцию swap

2023-11-15 05:42 UTC, bleb1 commented on tasks/matrix/tasks/22/solution.h
> +        temp = matrix[mini_x][j];
Исправил, сделал через указатели

2023-11-15 05:42 UTC, bleb1 commented on tasks/matrix/tasks/22/solution.h
> +int32_t MinInd(int32_t a, int32_t b, int32_t i, int32_t mini_x) {
есть

2023-11-20 13:09 UTC, Maxsmile123 requested changes

2023-11-20 13:09 UTC, Maxsmile123 commented on tasks/matrix/tasks/22/file.txt
> +3
Поправишь?

2023-11-20 19:02 UTC, bleb1 commented on tasks/matrix/tasks/22/file.txt
> +3
Да, конечно, почему-то не увидел этот комментарий.
А так прога с любой матрицей справится)

2023-11-27 09:43 UTC, merged