Linerization - Prokofev
Maxsmile123/ZZZ-Computer-Science-Course pull request #246
Opened 2023-11-13 08:13 UTC by rezect

2023-11-14 14:12 UTC, Maxsmile123 requested changes

2023-11-14 14:12 UTC, Maxsmile123 commented on tasks/linerization/tasks/13/solution.h
> +typedef int32_t Intt;
Зачем?

2023-11-14 14:12 UTC, Maxsmile123 commented on tasks/linerization/tasks/13/solution.h
> +            scanf("%d", two_dmentional_array[i] + j);
Сканф в CI использовать не нужно. Проинициализируй руками, либо через файл

2023-11-14 14:12 UTC, Maxsmile123 commented on tasks/linerization/tasks/13/solution.h
> +    Intt sost = -1;  // для прохода вверх - 1, вниз - 0, по диагонали - -1;
translit nelza ispolzovat - eto krinj

2023-11-14 14:12 UTC, Maxsmile123 commented on tasks/linerization/tasks/13/solution.h
> +    while (k11 != -1 && k21 != -1) {
Вынеси функцию обхода матрицы в отдельную функцию

2023-11-14 14:12 UTC, Maxsmile123 commented on tasks/linerization/tasks/13/solution.h
> +    // Вывод массива final_matrix
Сделай вывод изначальной матрицы и линеризуемого результата

2023-11-17 14:46 UTC, rezect commented on tasks/linerization/tasks/13/solution.h
> +typedef int32_t Intt;
:)

2023-11-20 13:19 UTC, Maxsmile123 requested changes

2023-11-20 13:19 UTC, Maxsmile123 commented on tasks/linerization/tasks/13/solution.h
> +    Matrix matrix = (Matrix)malloc(sizeof(int32_t*) * strings * columns);
Не многовато памяти выделил?

2023-11-20 13:19 UTC, Maxsmile123 commented on tasks/linerization/tasks/13/solution.h
> +    int32_t strings = 4;
Лучше использовать rows

2023-11-20 13:19 UTC, Maxsmile123 commented on tasks/linerization/tasks/13/solution.h
> +    for (int i = 0; i < strings; ++i) {
Давай вынесем распечатку в отдельную функцию

2023-11-20 13:19 UTC, Maxsmile123 commented on tasks/linerization/tasks/13/solution.h
> +    for (int i = 0; i < 16; i++) {
Аналогично

2023-11-25 22:14 UTC, Maxsmile123 approved these changes

2023-11-25 22:14 UTC, merged