matrix34
Maxsmile123/ZZZ-Computer-Science-Course pull request #248
Opened 2023-11-16 21:14 UTC by SurovIvan

2023-11-20 13:34 UTC, Maxsmile123 requested changes

2023-11-20 13:34 UTC, Maxsmile123 commented on tasks/matrix/tasks/34/solution.h
> +    FILE* file_matrix = fopen("../tasks/matrix/tasks/34/matrix.txt", "r");
А если файл не удалось открыть? Добавь обработку ошибки в таком случае

2023-11-21 08:32 UTC, SurovIvan commented on tasks/matrix/tasks/34/solution.h
> +    FILE* file_matrix = fopen("../tasks/matrix/tasks/34/matrix.txt", "r");
Сделал

2023-11-25 08:51 UTC, Maxsmile123 approved these changes

2023-11-25 08:51 UTC, merged