MATRIX_VAR9_DNaypak
Maxsmile123/ZZZ-Computer-Science-Course pull request #258
Opened 2023-11-20 14:26 UTC by DmitryNai

2023-11-20 20:10 UTC, Maxsmile123 requested changes

2023-11-20 20:10 UTC, Maxsmile123 commented on tasks/matrix/tasks/9/solution.h
> +    int32_t* start_elements = (int32_t*)malloc((matrix_size - SHIFT) * sizeof(int32_t));
ммм.... не, не так. Что, если размер 1? А если 2? Уверен, твоя программа упадёт уже тут

2023-11-20 22:04 UTC, DmitryNai commented on tasks/matrix/tasks/9/solution.h
> +    int32_t matrix_size = *n * *n;
Исправил.

2023-11-20 22:05 UTC, DmitryNai commented on tasks/matrix/tasks/9/solution.h
> +    int32_t matrix_size = *n * *n;
> Давай сделаем так: `(*n) * (*n)` А то конструкция выглядит зловеще

Исправил.

2023-11-20 22:05 UTC, DmitryNai commented on tasks/matrix/tasks/9/solution.h
> +    int32_t index_scanf_matrix = matrix_size;
> Не понял название

Исправил. Изменил на "счётчик считывания элементов в матрицу"

2023-11-20 22:05 UTC, DmitryNai commented on tasks/matrix/tasks/9/solution.h
> +    int32_t count_of_new_elements = 0;
> new_elements_count

Исправил.

2023-11-20 22:06 UTC, DmitryNai commented on tasks/matrix/tasks/9/solution.h
> +    int32_t* start_elements = (int32_t*)malloc((matrix_size - SHIFT) * sizeof(int32_t));
> ммм.... не, не так. Что, если размер 1? А если 2? Уверен, твоя программа упадёт уже тут

Исправил. Теперь работает для любой матрицы.

2023-11-25 08:57 UTC, Maxsmile123 requested changes
Надо декомпозировать код

2023-11-25 08:57 UTC, Maxsmile123 commented on tasks/matrix/tasks/9/solution.h
> +Matrix InitializeMatrixAndShift(const char* filename, int32_t* n) {
InitializeMatrixAndShift -> название функции подсказывает, как её можно разделить на 2 =)

2023-11-26 09:35 UTC, DmitryNai commented on tasks/matrix/tasks/9/solution.h
> +Matrix InitializeMatrixAndShift(const char* filename, int32_t* n) {
> InitializeMatrixAndShift -> название функции подсказывает, как её можно разделить на 2 =)

Описал причину реализации.

2023-11-30 16:12 UTC, Maxsmile123 approved these changes
Ок

2023-11-30 16:13 UTC, merged