first try
Maxsmile123/ZZZ-Computer-Science-Course pull request #264
Opened 2023-11-24 14:35 UTC by UnlimitedRule8ook

2023-11-25 22:32 UTC, Maxsmile123 requested changes

2023-11-25 22:32 UTC, Maxsmile123 commented on tasks/linerization/tasks/17/solution.h
> +    // Рабоает только для квадратной матрицы четного порядка, т.к. начальная позиция выбирается специфично
Хорошо, а почему не попробовать написать алгоритм и для нечётного порядка? Получается, у тебя код работает только для половины случаем

2023-11-29 10:40 UTC, UnlimitedRule8ook commented on tasks/linerization/tasks/17/solution.h
> +    // Рабоает только для квадратной матрицы четного порядка, т.к. начальная позиция выбирается специфично
Теперь по-идее должно работать вообще с любым размером матрицы

2023-11-30 16:19 UTC, Maxsmile123 approved these changes
ok

2023-11-30 16:19 UTC, merged