matrix_var5_MGlebova
Maxsmile123/ZZZ-Computer-Science-Course pull request #267
Opened 2023-11-24 17:30 UTC by mashulyag

2023-11-25 23:22 UTC, Maxsmile123 requested changes

2023-11-25 23:22 UTC, Maxsmile123 commented on tasks/matrix/tasks/5/solution.h
> +    for (int i = 0; i < n; i++) {
Код распечатки матрицы можно вынести в функцию и избежать дублирования

2023-11-26 13:40 UTC, mashulyag commented on tasks/matrix/tasks/5/solution.h
> +    for (int i = 0; i < n; i++) {
Исправила

2023-11-30 16:22 UTC, Maxsmile123 approved these changes

2023-11-30 16:22 UTC, merged