taylor18
Maxsmile123/ZZZ-Computer-Science-Course pull request #275
Opened 2023-11-25 22:24 UTC by SurovIvan

2023-12-01 16:05 UTC, Maxsmile123 requested changes

2023-12-01 16:05 UTC, Maxsmile123 commented on tasks/taylor/tasks/18/solution.h
> +double Taylor(double x, int32_t iterations) {
Очень неэффективно каждый раз считать Тэйлора заново. Попробуй накапливать результат, а потом к нему прибавлять следующий

2023-12-01 16:05 UTC, Maxsmile123 commented on tasks/taylor/tasks/18/solution.h
> +    BoundaryRowsTable;
Выглядит странно. Почему решил делать это в виде макросов?

2023-12-01 19:07 UTC, SurovIvan commented on tasks/taylor/tasks/18/solution.h
> +    BoundaryRowsTable;
Думал, что так будет выглядеть более понятно (не будет нагромождать). Сделал по-другому.

2023-12-03 16:41 UTC, Maxsmile123 commented on tasks/taylor/tasks/18/solution.h
> +        if (fabs(sum_taylor_row - Func(current_x)) < DBL_EPSILON * accuracy_factor) {
Почему бы не вычислить значение в функции один раз за пределами цикла?

2023-12-03 16:51 UTC, Maxsmile123 commented on tasks/taylor/tasks/18/solution.h
> +    return sum_taylor_row += pow(-1, i + 1) * (pow(x, 2 * i + 1) / (4 * pow(i, 2) - 1));
Можно просто возвращать ```pow(-1, i + 1) * (pow(x, 2 * i + 1) / (4 * pow(i, 2) - 1))```

2023-12-03 16:51 UTC, Maxsmile123 commented on tasks/taylor/tasks/18/solution.h
> +        sum_taylor_row = Taylor(current_x, iteration, sum_taylor_row);
А тут сделать так:
```sum_taylor_row += Taylor(current_x, iteration)```

2023-12-04 11:17 UTC, merged