BITTSETS_16_PERMYAKOV.h
Maxsmile123/ZZZ-Computer-Science-Course pull request #276
Opened 2023-11-26 08:45 UTC by German2104

2023-12-22 12:01 UTC, sergey162 commented on tasks/bitsets/tasks/16/solution.h
> +    unsigned int letters_set_1 = 0;
лучше оставь Bitset
typedef uint32_t Bitset;  он тебя не должен смущать, потому что это другое название того же типа
Bitset a <=> uin32_t a 
просто может это не понравиться проверяющему, поскольку я в свое время проигнорировал Matrix и написал int32_t** вроде, и пришлось исправить

2023-12-22 12:15 UTC, sergey162 commented on tasks/bitsets/tasks/16/solution.h
> +    if (c < 'a' || c > 'z' || c == 'a' || c == 'u' || c == 'o' || c == 'e' || c == 'i') {
чтобы избежать таких довольно сложных и не оптимальных конструкций(просто у меня была такая же история в if куча условий) . можно сделать следующее
сделай множество всех гласных букв Bitset (name) = число, которое включает все все гласные например 110100110011 - взято от балды но надо чтоб на позициях согласных стояли единички а на позиции гласных стояли бы нолики. можешь взять какой то просто онлайн представлятор двоичных чисел в десятиричную и прикинуть что будет за число.
Далее создаешь два множества, для первого слово и для второго
заполняешь первое слово побитовыми сдвигами, делаешь логическое & с всеми гласными
аналогично поступаешь с вторым словом
далее просто сравниваешь эти множество оператором ==

2023-12-23 12:22 UTC, Maxsmile123 requested changes

2023-12-23 12:22 UTC, Maxsmile123 commented on tasks/bitsets/tasks/16/solution.h
> +    if (c < 'a' || c > 'z' || c == 'a' || c == 'u' || c == 'o' || c == 'e' || c == 'i') {
Соглашусь - через множество было бы круче. Но уже поздно.

2023-12-23 12:22 UTC, Maxsmile123 commented on tasks/bitsets/tasks/16/solution.h
> -typedef uint32_t Bitset;
Не, это уже плохо

2023-12-23 12:22 UTC, Maxsmile123 commented on tasks/bitsets/tasks/16/solution.h
> +    unsigned int letters_set_1 = 0;
BitSet поможет читателю кода понять, что ты работаешь с битсетом, а не просто с числом рандомным

2024-01-04 15:52 UTC, Maxsmile123 approved these changes

2024-01-04 15:52 UTC, merged