FSM
Maxsmile123/ZZZ-Computer-Science-Course pull request #279
Opened 2023-11-26 12:09 UTC by sergey162

2023-12-01 16:28 UTC, Maxsmile123 requested changes

2023-12-01 16:28 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/2/FSM.h
> +    //  "/\*([^*]|[\n\r]|(\*+([^*/]|[\n\r])))*\*+/" regex
Напиши на каких тестовых данных ты её проверял. Также в комментариях в коде

2023-12-01 16:28 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/2/FSM2.drawio
Хочется скриншот, а не этот файл

2023-12-01 16:28 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/2/shared_header.c
> +    FINDFIRSTSYMBOLCOMMENTS2,
Не понял, что означает цифра 1 или 2. Стоит подумать над названиями (желательно ещё короткими)

2023-12-01 16:28 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/2/shared_header.c
> +    int step;
Оно тебе и правда нужно для задачи?

2023-12-01 16:28 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/2/shared_header.c
> +    int count;
слишком абстрактно

2023-12-01 16:28 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/2/state.c
> +StateName FindCountWords(StateMachine* sm, char ch) {
У тебя нет такого названия состояния в StateName

2023-12-01 16:28 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/2/state.c
> +    if (ch == ' ' && sm->lastsym != ' ') {
А если текст выглядит так:
```
/*Hello
How
Are
You?*/
```

2023-12-01 16:28 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/2/state.c
> +    if (ch == ' ' && sm->lastsym != ' ') {
Ты не учитываешь, что слово может быть разделено \n
а во вторых живёшь в предположении, что слова разделены двумя пробелами ( а это не так)

2023-12-01 16:28 UTC, Maxsmile123 commented on tasks/finite_state_machine/variants.md
> +| Усов Сергей Евгеньевич | [2](./tasks/32) |
Ссылку тоже нужно заменить

2023-12-01 16:28 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/2/state.c
> +    st[i].name = (StateName)i;
Почему решил отказаться от удобной инициализации из примера?

2023-12-01 17:10 UTC, sergey162 commented on tasks/finite_state_machine/tasks/2/state.c
> +    if (ch == ' ' && sm->lastsym != ' ') {
а во вторых живёшь в предположении, что слова разделены двумя пробелами ( а это не так)

 с одним отлично работает

2023-12-01 17:11 UTC, sergey162 commented on tasks/finite_state_machine/tasks/2/state.c
> +    st[i].name = (StateName)i;
не пускает меня проверялка

2023-12-01 17:29 UTC, sergey162 commented on tasks/finite_state_machine/tasks/2/state.c
> +    if (ch == ' ' && sm->lastsym != ' ') {
просто если 2 и более пробела то я как раз и не увеличваю счетчик

2023-12-01 17:32 UTC, sergey162 commented on tasks/finite_state_machine/tasks/2/state.c
> +StateName FindCountWords(StateMachine* sm, char ch) {
сделал

2023-12-01 17:32 UTC, sergey162 commented on tasks/finite_state_machine/tasks/2/shared_header.c
> +    int count;
исправил

2023-12-01 17:32 UTC, sergey162 commented on tasks/finite_state_machine/tasks/2/shared_header.c
> +    int step;
исправил

2023-12-02 09:11 UTC, Maxsmile123 requested changes
Допустим, ОК - надо поправить мелкие правки

2023-12-02 09:11 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/2/FSM.h
> -#pragma once
Не удаляй плиз

2023-12-02 09:11 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/2/shared_header.c
> +    char lastsym;
last_sym

2023-12-02 09:11 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/2/state.c
> +            //--sm->count;
remove

2023-12-04 17:35 UTC, Maxsmile123 approved these changes

2023-12-04 17:35 UTC, merged