Taylor17
Maxsmile123/ZZZ-Computer-Science-Course pull request #284
Opened 2023-11-27 14:38 UTC by sergey162

2023-12-01 16:38 UTC, Maxsmile123 requested changes

2023-12-01 16:38 UTC, Maxsmile123 commented on tasks/taylor/tasks/17/solution.h
> +double NatyralLog(double x) {
А зачем? Есть же ln из math.h

2023-12-01 16:38 UTC, Maxsmile123 commented on tasks/taylor/tasks/17/solution.h
> +double Degree(double exp, uint8_t n) {
А зачем? Используй math.h

2023-12-01 16:38 UTC, Maxsmile123 commented on tasks/taylor/tasks/17/solution.h
> +double ResultInPoint(double x, uint16_t iterations, uint8_t precision) {
Название не понятное

2023-12-01 16:38 UTC, Maxsmile123 commented on tasks/taylor/tasks/17/solution.h
> +        result += (double)1 / (2 * i + 1) * Degree((x - 1.0) / (x + 1.0), 2 * i + 1);
Ты для каждой итерации заново считаешь Тэйлора. А зачем? Давай как-то накапливать результат который уже посчитали и прибавлять к нему новые члены

2023-12-01 16:38 UTC, Maxsmile123 commented on tasks/taylor/tasks/17/solution.h
> +void PrintString(double x, double tailor_result, double func_result) {
Не понятно, что за PrintString

2023-12-01 16:44 UTC, sergey162 commented on tasks/taylor/tasks/17/solution.h
> +double NatyralLog(double x) {
по дефолту log - натуральный логарифм

2023-12-01 16:44 UTC, sergey162 commented on tasks/taylor/tasks/17/solution.h
> +double Degree(double exp, uint8_t n) {
решил сам написать функцию возведения в степень

2023-12-04 17:53 UTC, Maxsmile123 requested changes

2023-12-04 17:53 UTC, Maxsmile123 commented on tasks/taylor/tasks/17/solution.h
> +long double CalcPerIter(long double x, int iter) {
Лучше связать название функции с Тэйлором. Например, TaylorSeriesTerm (Член ряда Тейлора)

2023-12-04 17:53 UTC, Maxsmile123 commented on tasks/taylor/tasks/17/solution.h
> +bool PositiveCalc(long double x, long double tailor_result, uint8_t precision) {
Название не по кодстайлу.

Следует назвать лучше: IsBreakCalc

2023-12-04 17:53 UTC, Maxsmile123 commented on tasks/taylor/tasks/17/solution.h
> +    printf("iter = %d  x = %.3Lf Tailor = %.12Lf Func = %.12Lf\n", iter, x, tailor_result, func_result);
Печатать нужно кол-во итераций, которые понадобились для расчёта Тэйлора, а не просто счётчик

2023-12-04 19:35 UTC, sergey162 commented on tasks/taylor/tasks/17/solution.h
> +    printf("iter = %d  x = %.3Lf Tailor = %.12Lf Func = %.12Lf\n", iter, x, tailor_result, func_result);
исправил все недочеты

2023-12-08 17:34 UTC, Maxsmile123 requested changes

2023-12-08 17:34 UTC, Maxsmile123 commented on tasks/taylor/tasks/17/solution.h
> +        PrintTable(x, Func(x), taylor_result, num_taylor_it);
Выведи результат так, как требует того задание. 
В методичке представлена таблица. Сейчас у тебя даже цифры слипаются

2023-12-10 01:52 UTC, Maxsmile123 approved these changes

2023-12-10 01:52 UTC, merged