FSM - Prokofev
Maxsmile123/ZZZ-Computer-Science-Course pull request #297
Opened 2023-12-01 18:26 UTC by rezect

2023-12-05 09:14 UTC, DmitryNai commented on tasks/finite_state_machine/tasks/6/fsm_transition.h
> +void Transition(Machine* machine, FILE* file) {
Не не, не так. На занятии мы придумали куда более лучшее оформление, избегая такой сложной конструкции. через if. Оно лежит в папке exemples.

2023-12-05 09:14 UTC, DmitryNai commented on tasks/finite_state_machine/tasks/6/diagram.drawio
> +</mxfile>
Лучше убрать этот файл и просто прикрепить скрин диаграммы.

2023-12-08 19:04 UTC, Maxsmile123 requested changes

2023-12-08 19:04 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/6/diagram.drawio
Хочу jpg

2023-12-08 19:04 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/6/fsm_transition.h
> +void Transition(Machine* machine, FILE* file) {
Согласен. Код выглядит чертовски сложно. Думаю, надо даже будет на защиту по этой задаче сходить

2023-12-08 19:04 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/6/fsm_transition.h
> +bool IsValidCIdentifier(const char* word) {
А за это лайк

2023-12-12 20:48 UTC, Maxsmile123 requested changes

2023-12-12 20:48 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/6/fsm_transition.h
> +void Transition(Machine* machine, FILE* file) {
Ты не понял суть дизайна. Мы решили избавиться от if else или switch путём добавления структуры Состояния - это имя + функция, которую оно выполняет. По итогу, мы получим хорошо масштабируемый код - хочешь расширить состояния - добавь функцию, название и проинициализируй. Просто и красиво. В твоём коде придётся очень долго копаться, чтобы разобраться где и что меняется + сложно модифицировать.

Я готов принять такой дизайн за половину баллов.

2023-12-14 04:17 UTC, rezect commented on tasks/finite_state_machine/tasks/6/fsm_transition.h
> +void Transition(Machine* machine, FILE* file) {
Я защищался, вы сказали вроде норм из-за того, что я пропустил лабу по фсм как раз, но могу переделать, только не уверен что скоро получится

2023-12-14 04:18 UTC, rezect commented on tasks/finite_state_machine/tasks/6/fsm_transition.h
> +void Transition(Machine* machine, FILE* file) {
> Ты не понял суть дизайна. Мы решили избавиться от if else или switch путём добавления структуры Состояния - это имя + функция, которую оно выполняет. По итогу, мы получим хорошо масштабируемый код - хочешь расширить состояния - добавь функцию, название и проинициализируй. Просто и красиво. В твоём коде придётся очень долго копаться, чтобы разобраться где и что меняется + сложно модифицировать.
> 
> Я готов принять такой дизайн за половину баллов.

Я защищался, вы сказали вроде норм из-за того, что я пропустил лабу по фсм как раз, но могу переделать, только не уверен что скоро получится

2023-12-23 12:23 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/6/fsm_transition.h
> +void Transition(Machine* machine, FILE* file) {
То, что ты пропустил занятие не означает, что тебе разрешено писать плохой код :)
Надо хороший дизайн использовать

2024-01-04 09:32 UTC, rezect commented
я согласен на половину баллов

2024-01-04 09:33 UTC, rezect commented on tasks/finite_state_machine/tasks/6/fsm_transition.h
> +void Transition(Machine* machine, FILE* file) {
я согласен на половину баллов

2024-01-04 09:33 UTC, rezect commented on tasks/finite_state_machine/tasks/6/fsm_transition.h
> +void Transition(Machine* machine, FILE* file) {
> То, что ты пропустил занятие не означает, что тебе разрешено писать плохой код :) Надо хороший дизайн использовать

я согласен на половину баллов

2024-01-04 15:57 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/6/fsm_transition.h
> +void Transition(Machine* machine, FILE* file) {
а половину баллов никто и не предлагал.

2024-01-07 15:14 UTC, merged