bitsets_var28_MGlebova
Maxsmile123/ZZZ-Computer-Science-Course pull request #305
Opened 2023-12-03 13:36 UTC by mashulyag

2023-12-04 16:04 UTC, nimelnikova requested changes

2023-12-04 16:30 UTC, mashulyag commented on tasks/bitsets/tasks/28/solution.h
> +bool VowelWord(Bitset num, Bitset a, Bitset b) {
Думаю, что лучше будет WordContainsOnlyVowels

2023-12-04 16:30 UTC, mashulyag commented on tasks/bitsets/tasks/28/solution.h
> +#include <ctype.h>
Я просто код переделывала и забыла про неё

2023-12-08 19:12 UTC, Maxsmile123 approved these changes

2023-12-08 19:12 UTC, merged