geometry_4
Maxsmile123/ZZZ-Computer-Science-Course pull request #311
Opened 2023-12-04 14:58 UTC by Popov-Vladimir-1

2023-12-04 15:15 UTC, sergey162 commented on tasks/geometry/tasks/4/solution.h
> +    int flag = 1;
тебе надо  проделать следующие действия
собрать проект в папке build и прописать
../tools/run_linter.sh... - полностью есть в инструкции  path(где он путь к папке с задачей)
предварительно это проверку надо скачать тоже есть в инструции

2023-12-04 15:18 UTC, sergey162 commented on tasks/geometry/tasks/4/solution.h
> +double root(double num) {
сомневаюсь что нужен double. Эта лаба выдавалась до того как был рассказан показан вещественные числа. Лучше бы не пользоваться им

2023-12-04 15:25 UTC, Popov-Vladimir-1 commented on tasks/geometry/tasks/4/solution.h
> +double root(double num) {
я ищу корень, так что лучше double

2023-12-05 05:06 UTC, Popov-Vladimir-1 commented on tasks/geometry/tasks/4/solution.h
> +        if (first > third) {
я за понятность,  а не краткость

2023-12-05 05:08 UTC, Popov-Vladimir-1 commented on tasks/geometry/tasks/4/solution.h
> +const int thirty = 30;
Магические константы предлагаешь?

2023-12-05 07:17 UTC, sergey162 commented on tasks/geometry/tasks/4/solution.h
> +const int thirty = 30;
Не предлагаю, просто нам сказали,что очевидные цифры или из формул можно и так писать

2023-12-05 07:17 UTC, sergey162 commented on tasks/geometry/tasks/4/solution.h
> +const int thirty = 30;
И могут наругаться по этому поводу

2023-12-08 19:30 UTC, Maxsmile123 requested changes

2023-12-08 19:30 UTC, Maxsmile123 commented on tasks/geometry/tasks/4/solution.h
> +        if (first > third) {
Выйдет короче, но разобрать это будет чертовски сложно:
```return a > b ? a > c ? a : c : b > c ? b : c;```

2023-12-08 19:30 UTC, Maxsmile123 commented on tasks/geometry/tasks/4/solution.h
> +        if (first > third) {
Но мне лично тернарный тоже больше нравится

2023-12-08 19:30 UTC, Maxsmile123 commented on tasks/geometry/tasks/4/solution.h
> +int CheckZONE(Point p) {
CheckZone

2023-12-09 10:30 UTC, Maxsmile123 approved these changes

2023-12-09 10:30 UTC, merged

2023-12-09 13:16 UTC, sergey162 commented
Отличная работа