Dorofeev | Taylor 10var
Maxsmile123/ZZZ-Computer-Science-Course pull request #323
Opened 2023-12-08 16:46 UTC by JDorof

2023-12-08 17:59 UTC, Maxsmile123 requested changes

2023-12-08 17:59 UTC, Maxsmile123 commented on tasks/taylor/tasks/10/solution.h
> +double FirstFactor(uint32_t iteration) {
А нельзя это оформить как pow(-1, it - 1)?
И не нужна функция для этого отдельная

2023-12-08 17:59 UTC, Maxsmile123 commented on tasks/taylor/tasks/10/solution.h
> +        y += FirstFactor(iteration) * Numerator(iteration, x) / Denumerator(iteration);
А inf у тебя вылезает на 16-ой итерации.
Если мы посчитаем факториал: (16 * 2)! = 263130836933693530167218012160000000

Я не уверен, что оно влезло в дабл. Но если и влезло, то деление на эту фигню ничего хорошего не даст, конечно

2023-12-11 11:27 UTC, Maxsmile123 requested changes

2023-12-11 11:27 UTC, Maxsmile123 commented on tasks/taylor/tasks/10/solution.h
> +double Indent(double a, double b, int32_t n) {
Step

2023-12-11 11:27 UTC, Maxsmile123 commented on tasks/taylor/tasks/10/solution.h
> +        if (abs(y_func - y) < DBL_EPSILON) {
DBL_EPSILON * precision. У нас обязательно должен быть выбор точности вычислений

2023-12-11 11:27 UTC, Maxsmile123 commented on tasks/taylor/tasks/10/solution.h
> +    double previous_y = pow(x, 2.0);
prev_y

2023-12-11 11:27 UTC, Maxsmile123 commented on tasks/taylor/tasks/10/solution.h
> +    double new_y = 0;
next_y

2023-12-11 11:27 UTC, Maxsmile123 commented on tasks/taylor/tasks/10/solution.h
> +    for (int32_t iteration = 2u; iteration < 100; ++iteration) {
почему начинаешь с 2?

2023-12-11 11:27 UTC, Maxsmile123 commented on tasks/taylor/tasks/10/solution.h
> +        new_y = previous_y * (double)((-4) * pow(x, 2.0)) / (double)((iteration * 2 - 1) * (iteration * 2));
Функцию вычисления члена Тэйлора вынеси в отдельную функцию

2023-12-12 19:46 UTC, JDorof commented on tasks/taylor/tasks/10/solution.h
> +    for (int32_t iteration = 2u; iteration < 100; ++iteration) {
Начинаю с двух, так как за циклом фактически делается первая итерация.

2023-12-12 20:55 UTC, Maxsmile123 approved these changes

2023-12-12 20:57 UTC, merged