num_var3_MGlebova
Maxsmile123/ZZZ-Computer-Science-Course pull request #324
Opened 2023-12-08 19:46 UTC by mashulyag

2023-12-12 21:10 UTC, Maxsmile123 requested changes
Надо сходить на защиту

2023-12-12 21:10 UTC, Maxsmile123 commented on tasks/numerical_methods/tasks/3/solution.h
> +double CalculatingOfDerivatie(double x) {
Func2Derivative

2023-12-12 21:10 UTC, Maxsmile123 commented on tasks/numerical_methods/tasks/3/solution.h
> +    while (fabs((xn1 - xn0) / (1.0 - ((xn1 - xn0) / (xn1 - xn0)))) > DBL_EPSILON) {
Почему строгое >?

2023-12-12 21:10 UTC, Maxsmile123 commented on tasks/numerical_methods/tasks/3/solution.h
> +    OutputAnswer(start_section_1, end_section_1, Func1, MethodOfIterative, 10, APPROXIMATION_VALUE_1);
что за 10? Почему 10? Лучше вынести в константу

2023-12-12 21:19 UTC, mashulyag commented on tasks/numerical_methods/tasks/3/solution.h
> +double CalculatingOfDerivatie(double x) {
В принципе, логично. Исправила

2023-12-12 21:19 UTC, mashulyag commented on tasks/numerical_methods/tasks/3/solution.h
> +    while (fabs((xn1 - xn0) / (1.0 - ((xn1 - xn0) / (xn1 - xn0)))) > DBL_EPSILON) {
очепяточка

2023-12-23 12:27 UTC, Maxsmile123 approved these changes

2023-12-23 12:28 UTC, merged