FSM_39 Ивченко
Maxsmile123/ZZZ-Computer-Science-Course pull request #327
Opened 2023-12-08 20:20 UTC by Matvey26

2023-12-08 20:38 UTC, Matvey26 commented
Физик, инженер и математик принимают участие в эксперименте. Каждого запирают в комнате с банкой бобров.
Через три дня исследователи по очереди открывают двери.

В первой комнате они обнаруживают довольного физика, покрывающего пол и стены формулами. Консервная банка аккуратно открыта. На вопрос как он это сделал он отвечает:
— О, я просто приложил нагрузку к точкам напряжения.

В следующей комнате инженер, он сидит в углу, а рядом раскуроченая банка. На вопрос как открыл отвечает:
— Я наработал её до точки отказа.

Наконец, открывают третью дверь.
Там на полу сидит математик, обнимает банку, качается взад–вперёд и бормочет:
— "Предположим, что банка открыта, предположим, что банка открыта, предположим, что банка открыта"

2023-12-12 21:53 UTC, Maxsmile123 requested changes

2023-12-12 21:53 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/39/shared_header.h
> +const int64_t HEX_LENGTH = 4;
А зачем ограничивать длину числа?

2023-12-13 06:40 UTC, Matvey26 commented on tasks/finite_state_machine/tasks/39/shared_header.h
> +const int64_t HEX_LENGTH = 4;
Я давно ещё спрашивал в телеграмме, как будут выглядеть ввод в моём задании, и тогда вы сказали посмотреть, как хранятся числа в памяти компьютера, потому там есть неочевидный реверс. Поэтому я ограничиваю длину числа

2023-12-23 12:32 UTC, Maxsmile123 approved these changes

2023-12-23 12:32 UTC, merged