Dorofeev | NumM 20var
Maxsmile123/ZZZ-Computer-Science-Course pull request #328
Opened 2023-12-08 21:05 UTC by JDorof

2023-12-23 12:34 UTC, Maxsmile123 requested changes

2023-12-23 12:34 UTC, Maxsmile123 commented on tasks/numerical_methods/tasks/20/solution.h
> +    printf("Newton's Method:      %lf\n", newton_result);
Выведи сравнение полученного результата с результатом, заданным в таблице

2023-12-23 13:06 UTC, JDorof commented on tasks/numerical_methods/tasks/20/solution.h
> +    printf("Newton's Method:      %lf\n", newton_result);
готово

2023-12-26 13:41 UTC, Maxsmile123 approved these changes

2023-12-26 13:41 UTC, merged