first
Maxsmile123/ZZZ-Computer-Science-Course pull request #345
Opened 2023-12-15 20:33 UTC by nimelnikova

2023-12-15 21:07 UTC, nimelnikova commented
Я немного усложнила код из-за рассмотрения всевозможных ошибок, поэтому он, наверное, выглядит громоздким. Но в нем реализуется ошибки считывания файла, недостаток двоичных чисел для ответа (< 3 штук) или вообще их отсутствие. Комменты там не делала. 
Также, чтобы не менять структуру функции MakeStates (проблема была с START END ERROR_STATE, использовала атрибут unused)

2023-12-23 15:29 UTC, Maxsmile123 requested changes

2023-12-23 15:29 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/31/FSM.h
> -#pragma once
Зачем?

2023-12-23 15:29 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/31/FSM.h
> +    rewind(file);                        // Возвращаем указатель в начало файла
Good advanced file programming. Too good

2023-12-23 15:29 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/31/FSM.h
> +bool OpenFile(FILE **file, const char *filename) {
Зачем тут указатель на указатель?

2023-12-23 15:29 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/31/FSM.h
Работу с файлами стоит вынести в отдельный файлик

2023-12-23 15:29 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/31/fsm_realization.h
> +        StateName next = sm->pipeline[sm->cur_state].action(sm);
Можно сразу так:
```
sm->cur_state = sm->pipeline[sm->cur_state].action(sm);
```

2023-12-23 15:29 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/31/shared_header.h
> +    char current_binary_state[33];  // Для хранения двоичного числа как строки
А если я захочу хранить число размера 64 бита? Давай вынесем число 32 в константы и будем писать что-то вроде такого:
```c
char current_binary_state[BITS_COUNT + 1];
```

2023-12-23 15:29 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/31/state.h
> +StateName ErrorState(StateMachine *sm __attribute__((unused))) {
Нужна ли нам функция для состояния, которая ничего не делает?

2023-12-23 15:29 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/31/state.h
> +StateName End(StateMachine *sm __attribute__((unused))) {
Нужна ли нам функция для состояния, которая ничего не делает?

2023-12-23 15:29 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/31/state.h
> +StateName Start(StateMachine *sm __attribute__((unused))) {
Нужна ли нам функция для состояния, которая ничего не делает?

2024-01-01 22:29 UTC, merged