NUM_18
Maxsmile123/ZZZ-Computer-Science-Course pull request #349
Opened 2023-12-16 20:13 UTC by TheOriginalMJKey

2023-12-17 15:49 UTC, sergey162 commented on tasks/numerical_methods/tasks/18/solution.h
> +        double delta = Func2(root) / (1.0 - 1.0 / (3.0 + sin(3.6 * root)));
Лучше не создавать переменную в цикле.

2023-12-17 16:03 UTC, sergey162 commented on tasks/numerical_methods/tasks/18/solution.h
> +    double tolerance = 1e-6;
Лучше использовать DBL_EPSILON. Готовое, библиотечное, наиболее точное

2023-12-17 16:03 UTC, sergey162 commented on tasks/numerical_methods/tasks/18/solution.h
> +    int max_iterations = 100000;
Лучше не ограничивать количество итераций каким конкретным значением.
А сделать через while(пока разница между твоими значениями > эпсилон)

2023-12-17 16:03 UTC, sergey162 commented on tasks/numerical_methods/tasks/18/solution.h
> +    int max_iterations = 100000;
и для красоты вынести в функцию

2023-12-17 16:04 UTC, sergey162 commented on tasks/numerical_methods/tasks/18/solution.h
> +    int max_iterations = 100000;
в таком случае дельта не понадобится даже

2023-12-17 21:20 UTC, sergey162 commented on tasks/numerical_methods/tasks/18/solution.h
> +    printf("%f\n", root1);
Тебе нужно сравнить результат метода с тем, что дан в таблице в задании. Сравнить -> распечатать рядом

2023-12-17 21:21 UTC, sergey162 commented on tasks/numerical_methods/tasks/18/solution.h
> +        if (Func1(root) == 0.0 || (upper_bound - lower_bound) <= tolerance) {
Аналогично для сравнение fabs
На паре было рассмотрены подобные примеры

2023-12-23 15:36 UTC, Maxsmile123 requested changes
А вот прислушался бы к комментариям Сергея и сейчас бы задача была б зачтена

2023-12-23 15:36 UTC, Maxsmile123 commented on tasks/numerical_methods/tasks/18/solution.h
> +        double delta = Func2(root) / (1.0 - 1.0 / (3.0 + sin(3.6 * root)));
Верно

2023-12-23 15:36 UTC, Maxsmile123 commented on tasks/numerical_methods/tasks/18/solution.h
> +        if (delta < 0) {
Just use fabs

2023-12-23 15:36 UTC, Maxsmile123 commented on tasks/numerical_methods/tasks/18/solution.h
> +    double tolerance = 1e-6;
tolerance - это не машинное эпсилон

2023-12-23 15:36 UTC, Maxsmile123 commented on tasks/numerical_methods/tasks/18/solution.h
> +    printf("%f\n", root1);
yes

2023-12-23 15:36 UTC, Maxsmile123 commented on tasks/numerical_methods/tasks/18/solution.h
> +        if (Func1(root) == 0.0 || (upper_bound - lower_bound) <= tolerance) {
that right.
Не понимаю почему ограничение итераций в 100000

2023-12-26 13:47 UTC, merged