FSM 3 Бельский
Maxsmile123/ZZZ-Computer-Science-Course pull request #353
Opened 2023-12-18 20:45 UTC by bleb1

2023-12-26 14:00 UTC, Maxsmile123 requested changes

2023-12-26 19:17 UTC, bleb1 commented on tasks/finite_state_machine/tasks/3/state.h
> +    ++sm->step;
убрал

2023-12-26 19:18 UTC, bleb1 commented on tasks/finite_state_machine/tasks/3/state.h
> +    if (ch == ' ') {
Понял, поменял

2023-12-26 19:18 UTC, bleb1 commented on tasks/finite_state_machine/tasks/3/Снимок экрана 2023-12-18 234417.png
понял, сделано

2023-12-27 13:42 UTC, Maxsmile123 requested changes

2023-12-27 13:42 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/3/realization.h
> +    sm->step = 0;
Не убрал

2023-12-27 13:42 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/3/state.h
> +    if (ch == '1') {
эм...это зачем?

2023-12-27 15:50 UTC, bleb1 commented on tasks/finite_state_machine/tasks/3/state.h
> +    if (ch == '1') {
Если не использовать ch в функции, то линтер ругается, а если убрать ch из функции, то ругается компилятор, я так понимаю, шаблон функций состояний один

2023-12-28 08:43 UTC, bleb1 commented on tasks/finite_state_machine/tasks/3/state.h
> +    if (ch == '1') {
исправил

2024-01-01 22:36 UTC, merged