taylor_7
Maxsmile123/ZZZ-Computer-Science-Course pull request #355
Opened 2023-12-19 20:00 UTC by mnlyuzina

2023-12-21 19:11 UTC, sergey162 commented on tasks/taylor/tasks/7/solution.h
> +        int iterations_count = 1;
Лучше не обьявлять в цикле переменные. и саму конструкцию(несколько циклов вычисления ) по функциям разнести.
Тебе про это 100% скажут при проверке

2023-12-26 14:27 UTC, Maxsmile123 requested changes

2023-12-26 14:27 UTC, Maxsmile123 commented on tasks/taylor/tasks/7/solution.h
>      return 0.0;
А это тут зачем?

2023-12-26 14:27 UTC, Maxsmile123 commented on tasks/taylor/tasks/7/solution.h
> +    while (fabsl(x - B) < LDBL_EPSILON * K || x < B) {
Зачем первое условие?
Второе условие по заданию так выглядит
```
x < B -> x <= B
```

2023-12-26 14:27 UTC, Maxsmile123 commented on tasks/taylor/tasks/7/solution.h
> +                printf(" %0.2Lf | %20.20Lf |% 20.15Lf | %5d |\n", x, sum_of_taylor, Func(x), iterations_count);
Почему у тебя первое число длиннее второго? Зачем?

2024-01-04 16:15 UTC, Maxsmile123 approved these changes
pow(x, iterations_count); Можно было считать намного эффективнее

2024-01-04 16:15 UTC, merged