linerization_27
Maxsmile123/ZZZ-Computer-Science-Course pull request #363
Opened 2023-12-24 12:09 UTC by mnlyuzina

2023-12-24 19:25 UTC, sergey162 commented on tasks/linerization/tasks/27/solution.h
> +    int32_t input_matrix[4][4] = {{10, 11, 12, 1}, {9, 16, 13, 2}, {8, 15, 14, 3}, {7, 6, 5, 4}};
Надо динамически память выделять malloc

2023-12-24 19:25 UTC, sergey162 commented on tasks/linerization/tasks/27/solution.h
> +typedef int32_t* Matrix;
вот это не правильно

2023-12-26 15:06 UTC, Maxsmile123 requested changes

2024-01-04 16:22 UTC, Maxsmile123 approved these changes

2024-01-04 16:22 UTC, merged