Dorofeev | FSM 26var
Maxsmile123/ZZZ-Computer-Science-Course pull request #374
Opened 2023-12-26 15:04 UTC by JDorof

2023-12-26 20:44 UTC, Maxsmile123 requested changes

2023-12-26 20:44 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/26/FSM.h
> +    while (true) {
while(res) ?

2023-12-26 20:44 UTC, Maxsmile123 commented on tasks/finite_state_machine/tasks/26/state.h
> +    if (sm->cur_char == '$') {
Это откуда такой символ взялся? Почему доллар?

2023-12-27 12:16 UTC, JDorof commented on tasks/finite_state_machine/tasks/26/state.h
> +    if (sm->cur_char == '$') {
Все поправил.

2024-01-01 22:39 UTC, Maxsmile123 approved these changes

2024-01-01 22:39 UTC, merged