bitsets_22
Maxsmile123/ZZZ-Computer-Science-Course pull request #376
Opened 2024-01-01 15:20 UTC by Popov-Vladimir-1

2024-01-01 15:23 UTC, sergey162 commented on tasks/bitsets/tasks/22/solution.h
> +    char text[] = "qwerty asdfg zxcvb q";  // scanf при необходимости
нельзя массив использовать char ов

2024-01-01 15:28 UTC, sergey162 commented
Идея:
1. Сделай множество  всех согласных
2. Сделай множество букв своего слова getchar + побитовые сдвиги как в примере
3. Сделай  логическое & c множеством всех согласных
4. пройдись в цикле for от 0 до 32 делай сдвиги и считай единицы через &1
5.  если их количество == 1 -> слово есть
6. в противном случае выведи, что таких слов нет

2024-01-01 15:30 UTC, sergey162 commented
Возможно, можно и проще, НО как сделал ты, точно нельзя

2024-01-01 22:45 UTC, Maxsmile123 requested changes

2024-01-01 22:45 UTC, Maxsmile123 commented on tasks/bitsets/tasks/22/solution.h
> +const int WORDS_IN_ALFABET = 26;
Слов в алфавите? Там буковки скорее

2024-01-01 22:45 UTC, Maxsmile123 commented on tasks/bitsets/tasks/22/solution.h
> +    char text[] = "qwerty asdfg zxcvb q";  // scanf при необходимости
Это как входные данные - пофег

2024-01-01 22:45 UTC, Maxsmile123 commented on tasks/bitsets/tasks/22/solution.h
> +        if (text[i] >= 'a' && text[i] <= 'z') {
А если буквы в заглавном регистре?

2024-01-07 15:19 UTC, Maxsmile123 approved these changes

2024-01-07 15:20 UTC, merged