Laboratorka_1
Maxsmile123/ZZZ-Computer-Science-Course pull request #39
Opened 2023-09-16 07:34 UTC by Stimch

ну типо вот

2023-09-16 18:05 UTC, Maxsmile123 requested changes

2023-09-16 18:05 UTC, Maxsmile123 commented on tasks/linux/tasks/4/2.bash
> + mv Jack_Daniels.cpp ..
В папку Party, а не просто куда-то выше

2023-09-16 18:05 UTC, Maxsmile123 commented on tasks/linux/tasks/4/6.bash
> + find -type f -name "backdoor.py" -o -name "trojan.py" -o -name "keylogger.py"
Не, у тебя следующие файлы не пройдут:
```
Aba_trojan.py 
TroJan.py
...
```

2023-09-22 13:44 UTC, Stimch commented
Доработал задания 2 и 6

2023-09-23 12:04 UTC, Maxsmile123 requested changes

2023-09-23 12:04 UTC, Maxsmile123 commented on tasks/linux/tasks/4/2.bash
> + mv Jack_Daniels.cpp ../../Party
Неверно, нужно было так:
```mv Jack_Daniels.cpp ../../Party```

2023-09-23 12:04 UTC, closed without merging