okay
Maxsmile123/ZZZ-Computer-Science-Course pull request #45
Opened 2023-09-16 17:21 UTC by UnlimitedRule8ook

man, это мой реквест, че тут комментить

2023-09-16 18:16 UTC, Maxsmile123 commented
Туда-туда, жду остальные задачи

2023-09-25 20:27 UTC, UnlimitedRule8ook commented
Я, короче, не разобрался в прошлый раз и перепутал номера заданий с номерами вариантов. Сейчас вот сделал, но уже поздно. А еще я не уверен в формулировках некоторых тасков, но готов исправлять, если что

2023-09-28 09:41 UTC, Maxsmile123 requested changes

2023-09-28 19:30 UTC, UnlimitedRule8ook commented
Исправил, как сделать лучше 7ую я не придумал

2023-10-07 09:49 UTC, closed without merging