Goryachkin V. Laba1 (Linux)
Maxsmile123/ZZZ-Computer-Science-Course pull request #48
Opened 2023-09-16 20:59 UTC by Winterfulllll

2023-09-18 15:57 UTC, Maxsmile123 requested changes

2023-09-18 15:57 UTC, Maxsmile123 commented on tasks/linux/tasks/2/1.bash
> +find . -type f -name "*.txt" -exec sh -c 'mv "$0" "${0%.txt}.md"' {} \;
Слишком сложно, можно намного проще

2023-09-18 15:57 UTC, Maxsmile123 commented on tasks/linux/tasks/2/6.bash
На файле, в котором записано это, не работает:
```
yandex.com: qwerty123

google.com: Qwerty123

vk.com: Qwerty123_
```

2023-09-18 15:57 UTC, Maxsmile123 commented on tasks/linux/tasks/2/8.bash
> +grep -n 'def' имя_файла
у меня скрипт почему-то выдал ещё и это:
```
#define CATCH_GIVEN( desc )
```
А я хотел только питоновские def искать :(

2023-09-18 20:04 UTC, Winterfulllll commented on tasks/linux/tasks/2/6.bash
Исходя из формулировки, после названия сайта должен быть пробел и потом только двоеточие

2023-09-21 23:32 UTC, Maxsmile123 approved these changes

2023-09-28 09:43 UTC, closed without merging