Laba1 variant5
Maxsmile123/ZZZ-Computer-Science-Course pull request #66
Opened 2023-09-24 21:09 UTC by GorbanArtemiy

я забыл сделать PR 3 дня назад АААА

2023-09-25 12:50 UTC, Maxsmile123 commented on README.md
Это не нужно удалять

2023-09-25 12:51 UTC, Maxsmile123 commented on tasks/linux/tasks/5/10.bash
> +find -name = a* !+ *.php
Получил вывод:
```
-bash: !+: event not found
```
Задача минус

2023-09-25 12:52 UTC, Maxsmile123 commented on tasks/linux/tasks/5/2.bash
> +touch Turing
Создать папку, а не файлы. Задача минус

2023-09-25 12:52 UTC, Maxsmile123 commented on tasks/linux/tasks/5/3.bash
> +chmod 764 run.py
Ты затираешь исходные права, требовалось лишь их расширить, либо ужать.
Задача минус

2023-09-25 12:53 UTC, Maxsmile123 commented on tasks/linux/tasks/5/4.bash
> +rm aba* *.py
Оно не так работает, задача минус

2023-09-25 12:53 UTC, Maxsmile123 commented on tasks/linux/tasks/5/5.bash
> +cp ty.go
Это неверно, нужно переместить в папку

2023-09-25 12:54 UTC, Maxsmile123 commented on tasks/linux/tasks/5/6.bash
> +chmod 000 virus.py
Запретить выполнение, а не чтение и запись. Задача неверная

2023-09-25 12:56 UTC, Maxsmile123 commented on tasks/linux/tasks/5/9.bash
> +find / tmp -type f -name ".*"
Не учитывается максимальная глубина поиска. Задача неверная.

2023-10-03 13:55 UTC, Maxsmile123 requested changes

2023-10-03 13:55 UTC, Maxsmile123 commented on tasks/linux/tasks/5/10.bash
> +find -name = a* != *.php
Попробуй у себя в консоли запустить эту утилиту. Что оно выведет? У меня выводит только ошибки

2023-10-03 13:55 UTC, Maxsmile123 commented on tasks/linux/tasks/5/2.bash
> +mkdir Turing
А можешь сделать всё в одну строчку? У mkdir есть для этого специальный параметр

2023-10-03 13:55 UTC, Maxsmile123 commented on tasks/linux/tasks/5/3.bash
> +chmod a+w run.py
Читать для всех, а не писать

2023-10-03 13:55 UTC, Maxsmile123 commented on tasks/linux/tasks/5/4.bash
> +rm ./aba *.py
У меня ошибки пишет

2023-10-07 07:46 UTC, GorbanArtemiy commented on tasks/linux/tasks/5/5.bash
> +cp -r golangCode
-r копирует все файлы в директорие

2023-10-18 20:58 UTC, closed without merging