Лабораторная1
Maxsmile123/ZZZ-Computer-Science-Course pull request #67
Opened 2023-09-25 14:06 UTC by Popov-Vladimir-1

Исправленная лабораторная №1
Теперь все там, где должно быть. Надеюсь на это.

2023-09-28 09:59 UTC, Maxsmile123 requested changes

2023-09-28 09:59 UTC, Maxsmile123 commented on tasks/linux/tasks/1/6.bash
> +grep -n +7 numbers.txt
Стригерится на строчку ```x+7```

2023-09-28 09:59 UTC, Maxsmile123 commented on tasks/linux/tasks/1/9.bash
> +find . -type f -size +1M -size -10M -exec ls -sh {} + | sort -hr | head -n 5
Это самое лучшее решение среди всех твоих коллег. +10 баллов дополнительно накидываю

2023-09-30 09:28 UTC, Maxsmile123 requested changes

2023-09-30 09:28 UTC, Maxsmile123 commented on tasks/linux/tasks/1/7.bash
> +grep -rl lol | sort -nr | head -5
Это не топ :(

2023-10-12 07:46 UTC, Popov-Vladimir-1 commented on tasks/linux/tasks/1/7.bash
> +grep -rl lol | sort -nr | head -5
теперь топ

2023-10-14 10:30 UTC, Maxsmile123 approved these changes

2023-10-14 10:35 UTC, closed without merging